### ISSUE TITLE
Plugin activation option does not appear

### ISSUE THREAD

**Issue by GokhanT7** [sokeio/laravel-grapesjs-builder-community#3]
Hi ! 

I made the adjustments in the video, but the option to activate the plugin does not appear. What could be the problem?
![grapesjs_ss_1](https://github.com/BytePlatform/laravel-builder-community/assets/132406556/72cf21c2-bfd5-414f-acdf-27380544201c)

**Comment by devhau** [comment]
I'm fixing it. Please wait a few more days.

**Comment by devhau** [comment]
@GokhanT7 Hello,
i fixed: https://github.com/sokeio/laravel-grapesjs-builder-community/issues/4#issuecomment-1826179817
